fix format

diff --git a/charts/operator-wandb/values.yaml b/charts/operator-wandb/values.yaml
--- a/charts/operator-wandb/values.yaml
+++ b/charts/operator-wandb/values.yaml
@@ -1049,11 +1049,11 @@ pre-hook:
             - bash
             - -c
             - |
-            OLD_VERSION=$(kubectl get deployment wandb-flat-run-fields-updater -o jsonpath="{.metadata.labels.app\.kubernetes\.io/version}" 2>/dev/null || echo "none")
-            if [ "$OLD_VERSION" = "0.33.0" ]; then
-              echo "Old deployment found with version $OLD_VERSION. Deleting..."
-              kubectl delete deployment wandb-flat-run-fields-updater --ignore-not-found
-            else
-              echo "Old deployment not found or already updated. Skipping deletion."
-            fi
+              OLD_VERSION=$(kubectl get deployment wandb-flat-run-fields-updater -o jsonpath="{.metadata.labels.app\.kubernetes\.io/version}" 2>/dev/null || echo "none")
+              if [ "$OLD_VERSION" = "0.33.0" ]; then
+                echo "Old deployment found with version $OLD_VERSION. Deleting..."
+                kubectl delete deployment wandb-flat-run-fields-updater --ignore-not-found
+              else
+                echo "Old deployment not found or already updated. Skipping deletion."
+              fi
           restartPolicy: Never
